import config from "@config/config.json";
import Base from "@layouts/Baseof";
import Cta from "@layouts/components/Cta";
import { markdownify } from "@lib/utils/textConverter";
import Image from "next/image";
import Link from "next/link";
import { Autoplay, Pagination } from "swiper";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/swiper.min.css";
import { getListPage } from "../lib/contentParser";

const PrivacyPolicy = ({ frontmatter }) => {
  const { banner, feature, services, workflow, call_to_action } = frontmatter;
  const { title } = config.site;

  return (
    <Base title={title}>
        <section className="section">
            <div className="container">
                <div className="row">
                    <h3 className="mb-4">Privacy Policy</h3>
                    <div className="">
                        <p>Effective date: November 10, 2020</p>
                        <p>Unipuzz Studio Pte. Ltd. (“us”, “we”, or “our”)
                            operates the monkidsstudio.com website and the Unipuzz Studio’ applications mobile
                            application (hereinafter referred to as the “Service”).
                        </p>
                        <p>This page informs you of our policies regarding the collection, use and
                            disclosure of personal data when you use our Service and the choices you have
                            associated with that data.
                        </p>
                        <p>We use your data to provide and improve the Service. By using the Service, you
                            agree to the collection and use of information in accordance with this policy.
                            Unless otherwise defined in this Privacy Policy, the terms used in this Privacy
                            Policy have the same meanings as in our Terms and Conditions.
                        </p>
                        <h4 className="mb-3 mt-3">Definitions</h4>
                        <ul>
                            <li>
                                <strong>Service</strong>
                                <p>Service means the Unipuzz Studio.com website and the Unipuzz Studio’
                                    applications mobile application operated by Unipuzz Studio Pte. Ltd.
                                </p>
                            </li>
                            <li>
                                <strong>Personal Data</strong>
                                <p>Personal Data means data about a living individual who can be identified
                                    from those data (or from those and other information either in our
                                    possession or likely to come into our possession).
                                </p>
                            </li>
                            <li>
                                <strong>Usage Data</strong>
                                <p>Usage Data is data collected automatically either generated by the use of
                                    the Service or from the Service infrastructure itself (for example, the
                                    duration of a page visit).
                                </p>
                            </li>
                            <li>
                                <strong>Cookies</strong>
                                <p>Cookies are small files stored on your device (computer or mobile
                                    device).
                                </p>
                            </li>
                            <li>
                                <strong>Data Controller</strong>
                                <p>Data Controller means the natural or legal person who (either alone or
                                    jointly or in common with other persons) determines the purposes for
                                    which and the manner in which any personal information are, or are to
                                    be, processed.
                                </p>
                                <p>For the purpose of this Privacy Policy, we are a Data Controller of your
                                    Personal Data.
                                </p>
                            </li>
                            <li>
                                <strong>Data Processors (or Service Providers)</strong>
                                <p>Data Processor (or Service Provider) means any natural or legal person
                                    who processes the data on behalf of the Data Controller.
                                </p>
                                <p>We may use the services of various Service Providers in order to process
                                    your data more effectively.
                                </p>
                            </li>
                            <li>
                                <strong>Data Subject (or User)</strong>
                                <p>Data Subject is any living individual who is using our Service and is the
                                    subject of Personal Data.
                                </p>
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Information Collection and Use</h4>
                        <p>We collect several different types of information for various purposes to provide
                            and improve our Service to you.
                        </p>
                        <h4 className="mb-3 mt-3">Types of Data Collected</h4>
                        <h5 className="mb-2 mt-2">Personal Data</h5>
                        <p>While using our Service, we may ask you to provide us with certain personally
                            identifiable information that can be used to contact or identify you
                            (“Personal Data”). Personally identifiable information may include,
                            but is not limited to:
                        </p>
                        <ul>
                            <li>Email address</li>
                            <li>Cookies and Usage Data</li>
                        </ul>
                        <p>We may use your Personal Data to contact you with newsletters, marketing or
                            promotional materials and other information that may be of interest to you. You
                            may opt out of receiving any, or all, of these communications from us by
                            following the unsubscribe link or the instructions provided in any email we
                            send.
                        </p>
                        <h5 className="mb-2 mt-2">Usage Data</h5>
                        <p>We may also collect information that your browser sends whenever you visit our
                            Service or when you access the Service by or through a mobile device
                            (“Usage Data”).
                        </p>
                        <p>This Usage Data may include information such as your computer’s Internet
                            Protocol address (e.g. IP address), browser type, browser version, the pages of
                            our Service that you visit, the time and date of your visit, the time spent on
                            those pages, unique device identifiers and other diagnostic data.
                        </p>
                        <p>When you access the Service with a mobile device, this Usage Data may include
                            information such as the type of mobile device you use, your mobile device unique
                            ID, the IP address of your mobile device, your mobile operating system, the type
                            of mobile Internet browser you use, unique device identifiers and other
                            diagnostic data.
                        </p>
                        <h5 className="mb-2 mt-2">Location Data</h5>
                        <p>We may use and store information about your location if you give us permission to
                            do so (“Location Data”). We use this data to provide features of our
                            Service, to improve and customise our Service.
                        </p>
                        <p>You can enable or disable location services when you use our Service at any time
                            by way of your device settings.
                        </p>
                        <h5 className="mb-2 mt-2">Tracking &amp; Cookies Data</h5>
                        <p>We use cookies and similar tracking technologies to track the activity on our
                            Service and we hold certain information.
                        </p>
                        <p>Cookies are files with a small amount of data which may include an anonymous
                            unique identifier. Cookies are sent to your browser from a website and stored on
                            your device. Other tracking technologies are also used such as beacons, tags and
                            scripts to collect and track information and to improve and analyse our Service.
                        </p>
                        <p>You can instruct your browser to refuse all cookies or to indicate when a cookie
                            is being sent. However, if you do not accept cookies, you may not be able to use
                            some portions of our Service.
                        </p>
                        <p>Examples of Cookies we use:</p>
                        <ul>
                            <li><strong>Session Cookies.</strong>&nbsp;We use Session Cookies to operate our
                                Service.
                            </li>
                            <li><strong>Preference Cookies.</strong>&nbsp;We use Preference Cookies to remember
                                your preferences and various settings.
                            </li>
                            <li><strong>Security Cookies.</strong>&nbsp;We use Security Cookies for security
                                purposes.
                            </li>
                            <li><strong>Advertising Cookies.</strong>&nbsp;Advertising Cookies are used to serve
                                you with advertisements that may be relevant to you and your interests.
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Use of Data</h4>
                        <p>Unipuzz Studio Pte. Ltd. uses the collected data for various purposes:</p>
                        <ul>
                            <li>To provide and maintain our Service</li>
                            <li>To notify you about changes to our Service</li>
                            <li>To allow you to participate in interactive features of our Service when you
                                choose to do so
                            </li>
                            <li>To provide customer support</li>
                            <li>To gather analysis or valuable information so that we can improve our
                                Service
                            </li>
                            <li>To monitor the usage of our Service</li>
                            <li>To detect, prevent and address technical issues</li>
                            <li>To provide you with news, special offers and general information about other
                                goods, services and events which we offer that are similar to those that you
                                have already purchased or enquired about unless you have opted not to
                                receive such information
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Legal Basis for Processing Personal Data under the General Data Protection
                            Regulation (GDPR)
                        </h4>
                        <p>If you are from the European Economic Area (EEA), Unipuzz Studio Pte. Ltd. legal basis
                            for collecting and using the personal information described in this Privacy
                            Policy depends on the Personal Data we collect and the specific context in which
                            we collect it.
                        </p>
                        <p>Unipuzz Studio Pte. Ltd. may process your Personal Data because:</p>
                        <ul>
                            <li>We need to perform a contract with you</li>
                            <li>You have given us permission to do so</li>
                            <li>The processing is in our legitimate interests and it is not overridden by
                                your rights
                            </li>
                            <li>For payment processing purposes</li>
                            <li>To comply with the law</li>
                        </ul>
                        <h4 className="mb-3 mt-3">Retention of Data</h4>
                        <p>Unipuzz Studio Pte. Ltd. will retain your Personal Data only for as long as is
                            necessary for the purposes set out in this Privacy Policy. We will retain and
                            use your Personal Data to the extent necessary to comply with our legal
                            obligations (for example, if we are required to retain your data to comply with
                            applicable laws), resolve disputes and enforce our legal agreements and
                            policies.
                        </p>
                        <p>Unipuzz Studio Pte. Ltd. will also retain Usage Data for internal analysis purposes.
                            Usage Data is generally retained for a shorter period of time, except when this
                            data is used to strengthen the security or to improve the functionality of our
                            Service, or we are legally obligated to retain this data for longer periods.
                        </p>
                        <h4 className="mb-3 mt-3">Transfer of Data</h4>
                        <p>Your information, including Personal Data, may be transferred to – and
                            maintained on – computers located outside of your state, province, country
                            or other governmental jurisdiction where the data protection laws may differ
                            from those of your jurisdiction.
                        </p>
                        <p>If you are located outside Singapore and choose to provide information to us,
                            please note that we transfer the data, including Personal Data, to Singapore and
                            process it there.
                        </p>
                        <p>Your consent to this Privacy Policy followed by your submission of such
                            information represents your agreement to that transfer.
                        </p>
                        <p>Unipuzz Studio Pte. Ltd. will take all the steps reasonably necessary to ensure that
                            your data is treated securely and in accordance with this Privacy Policy and no
                            transfer of your Personal Data will take place to an organisation or a country
                            unless there are adequate controls in place including the security of your data
                            and other personal information.
                        </p>
                        <h4 className="mb-3 mt-3">Disclosure of Data</h4>
                        <h5 className="mb-2 mt-2">Business Transaction</h5>
                        <p>If Unipuzz Studio Pte. Ltd. is involved in a merger, acquisition or asset sale, your
                            Personal Data may be transferred. We will provide notice before your Personal
                            Data is transferred and becomes subject to a different Privacy Policy.
                        </p>
                        <h5 className="mb-2 mt-2">Disclosure for Law Enforcement</h5>
                        <p>Under certain circumstances, Unipuzz Studio Pte. Ltd. may be required to disclose your
                            Personal Data if required to do so by law or in response to valid requests by
                            public authorities (e.g. a court or a government agency).
                        </p>
                        <h5 className="mb-2 mt-2">Legal Requirements</h5>
                        <p>Unipuzz Studio Pte. Ltd. may disclose your Personal Data in the good faith belief that
                            such action is necessary to:
                        </p>
                        <ul>
                            <li>To comply with a legal obligation</li>
                            <li>To protect and defend the rights or property of Unipuzz Studio Pte. Ltd.</li>
                            <li>To prevent or investigate possible wrongdoing in connection with the Service
                            </li>
                            <li>To protect the personal safety of users of the Service or the public</li>
                            <li>To protect against legal liability</li>
                        </ul>
                        <h4 className="mb-3 mt-3">Security of Data</h4>
                        <p>The security of your data is important to us but remember that no method of
                            transmission over the Internet or method of electronic storage is 100% secure.
                            While we strive to use commercially acceptable means to protect your Personal
                            Data, we cannot guarantee its absolute security.
                        </p>
                        <h4 className="mb-3 mt-3">Our Policy on “Do Not Track” Signals under the California Online
                            Protection Act (CalOPPA)
                        </h4>
                        <p>We do not support Do Not Track (“DNT”). Do Not Track is a preference
                            you can set in your web browser to inform websites that you do not want to be
                            tracked.
                        </p>
                        <p>You can enable or disable Do Not Track by visiting the Preferences or Settings
                            page of your web browser.
                        </p>
                        <h4 className="mb-3 mt-3">Your Data Protection Rights under the General Data Protection Regulation (GDPR)
                        </h4>
                        <p>If you are a resident of the European Economic Area (EEA), you have certain data
                            protection rights. Unipuzz Studio Pte. Ltd. aims to take reasonable steps to allow you
                            to correct, amend, delete or limit the use of your Personal Data.
                        </p>
                        <p>If you wish to be informed about what Personal Data we hold about you and if you
                            want it to be removed from our systems, please contact us.
                        </p>
                        <p>In certain circumstances, you have the following data protection rights:</p>
                        <ul>
                            <li><strong>The right to access, update or delete the information we have on
                                you.</strong>&nbsp;Whenever made possible, you can access, update or request
                                deletion of your Personal Data directly within your account settings
                                section. If you are unable to perform these actions yourself, please contact
                                us to assist you.
                            </li>
                            <li><strong>The right of rectification.</strong>&nbsp;You have the right to have your
                                information rectified if that information is inaccurate or incomplete.
                            </li>
                            <li><strong>The right to object.</strong>&nbsp;You have the right to object to our
                                processing of your Personal Data.
                            </li>
                            <li><strong>The right of restriction.</strong>&nbsp;You have the right to request
                                that we restrict the processing of your personal information.
                            </li>
                            <li><strong>The right to data portability.</strong>&nbsp;You have the right to be
                                provided with a copy of the information we have on you in a structured,
                                machine-readable and commonly used format.
                            </li>
                            <li><strong>The right to withdraw consent.</strong>&nbsp;You also have the right to
                                withdraw your consent at any time where Unipuzz Studio Pte. Ltd. relied on your
                                consent to process your personal information.
                            </li>
                        </ul>
                        <p>Please note that we may ask you to verify your identity before responding to such
                            requests.
                        </p>
                        <p>You have the right to complain to a Data Protection Authority about our
                            collection and use of your Personal Data. For more information, please contact
                            your local data protection authority in the European Economic Area (EEA).
                        </p>
                        <h4 className="mb-3 mt-3">Service Providers</h4>
                        <p>We may employ third party companies and individuals to facilitate our Service
                            (“Service Providers”), provide the Service on our behalf, perform
                            Service-related services or assist us in analysing how our Service is used.
                        </p>
                        <p>These third parties have access to your Personal Data only to perform these tasks
                            on our behalf and are obligated not to disclose or use it for any other purpose.
                        </p>
                        <p>Learn more about the login process with an email or Facebook connect at Accounts paragraph in <a href="https://static.Unipuzz Studio.com/terms-of-service/"> Terms and conditions</a>.
                        </p>
                        <h4 className="mb-3 mt-3">Analytics</h4>
                        <p>We may use third-party Service Providers to monitor and analyse the use of our
                            Service.
                        </p>
                        <ul>
                            <li>
                                <strong>Firebase</strong>
                                <p>Firebase is an analytics service provided by Google Inc.</p>
                                <p>You may opt-out of certain Firebase features through your mobile device
                                    settings, such as your device advertising settings or by following the
                                    instructions provided by Google in their Privacy Policy:&nbsp;<a href="./privacy?hl=en">https://policies.google.com/privacy?hl=en</a>
                                </p>
                                <p>We also encourage you to review the Google’s policy for
                                    safeguarding your data:&nbsp;<a href="./6004245">https://support.google.com/analytics/answer/6004245</a>.
                                </p>
                                <p>For more information on what type of information Firebase collects,
                                    please visit the Google Privacy &amp; Terms web page:&nbsp;<a href="./privacy?hl=en">https://policies.google.com/privacy?hl=en</a>
                                </p>
                            </li>
                            <li>
                                <strong>Unity Analytics</strong>
                                <p>Unity Analytics is provided by Unity Technologies.</p>
                                <p>For more information on what type of information Unity Analytics
                                    collects, please visit their Privacy Policy page:&nbsp;<a href="./privacy-policy">hhttps://unity3d.com/legal/privacy-policy</a>
                                </p>
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Advertising</h4>
                        <p>We may use third-party Service Providers to show advertisements to you to help
                            support and maintain our Service.
                        </p>
                        <ul>
                            <li>
                                <strong>AdMob by Google</strong>
                                <p>AdMob by Google is provided by Google Inc.</p>
                                <p>You can opt-out from the AdMob by Google service by following the
                                    instructions described by Google:&nbsp;<a href="./2662922?hl=en">https://support.google.com/ads/answer/2662922?hl=en</a>
                                </p>
                                <p>For more information on how Google uses the collected information, please
                                    visit the “How Google uses data when you use our partners’
                                    sites or app” page:&nbsp;<a href="./partners">http://www.google.com/policies/privacy/partners/</a>&nbsp;or
                                    visit the Privacy Policy of Google:&nbsp;<a href="./privacy">http://www.google.com/policies/privacy/</a>
                                </p>
                            </li>
                            <li>
                                <strong>AdColony</strong>
                                <p>AdColony is provided by Jirbo Inc.</p>
                                <p>You can opt-out from AdColony service by visiting the AdColony Opt-out
                                    page:&nbsp;<a href="http://www.adcolony.com/privacy-policy/opt-out">http://www.adcolony.com/privacy-policy/opt-out/</a>
                                </p>
                                <p>You can also opt-out from AdColony through the Digital Advertising
                                    Alliance in the USA&nbsp;<a href="./choices">http://www.aboutads.info/choices/</a>&nbsp;or opt-out
                                    using your mobile device settings.
                                </p>
                                <p>For more information AdColony, please visit the Privacy Policy of
                                    AdColony:&nbsp;<a href="./privacy-policy1">http://www.adcolony.com/privacy-policy/</a>
                                </p>
                            </li>
                            <li>
                                <strong>AppLovin</strong>
                                <p>AppLovin is provided by the AppLovin Corporation.</p>
                                <p>If you’d like to opt-out from AppLovin service, please visit the
                                    AppLovin Opt-out page:&nbsp;<a href="./optout">https://www.applovin.com/optout</a>
                                </p>
                                <p>If you’d like to learn more about AppLovin, please visit the
                                    Privacy Policy page of AppLovin:&nbsp;<a href="./privacy1">https://www.applovin.com/privacy</a>
                                </p>
                            </li>
                            <li>
                                <strong>Vungle</strong>
                                <p>Vungle is provided by Vungle Inc.</p>
                                <p>You can opt-out from Vungle service by following the instructions as
                                    described by Vungle on their Privacy Policy page:&nbsp;<a href="./privacy2">http://vungle.com/privacy/</a>
                                </p>
                                <p>For more information about Vungle, please visit Vungle Privacy Policy:&nbsp;<a href="./privacy2">http://vungle.com/privacy/</a>
                                </p>
                            </li>
                            <li>
                                <strong>Unity Ads</strong>
                                <p>Unity Ads is provided by Unity Technologies.</p>
                                <p>You can opt-out from Unity Ads service by following the instructions as
                                    described by Unity Technologies on their Privacy Policy page:&nbsp;<a href="./privacy-policy">https://unity3d.com/legal/privacy-policy</a>
                                </p>
                                <p>For more information about Unity Technologies, please visit Unity
                                    Technologies Privacy Policy:&nbsp;<a href="./privacy-policy">https://unity3d.com/legal/privacy-policy</a>
                                </p>
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Behavioral Remarketing</h4>
                        <p>Unipuzz Studio Pte. Ltd. uses remarketing services to advertise on third party websites
                            to you after you visited our Service. We and our third-party vendors use cookies
                            to inform, optimise and serve ads based on your past visits to our Service.
                        </p>
                        <ul>
                            <li>
                                <strong>Google Ads (AdWords)</strong>
                                <p>Google Ads (AdWords) remarketing service is provided by Google Inc.</p>
                                <p>You can opt-out of Google Analytics for Display Advertising and customise
                                    the Google Display Network ads by visiting the Google Ads Settings
                                    page:&nbsp;<a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a>
                                </p>
                                <p>Google also recommends installing the Google Analytics Opt-out Browser
                                    Add-on –&nbsp;<a href="./gaoptout">https://tools.google.com/dlpage/gaoptout</a>&nbsp;–
                                    for your web browser. Google Analytics Opt-out Browser Add-on provides
                                    visitors with the ability to prevent their data from being collected and
                                    used by Google Analytics.
                                </p>
                                <p>For more information on the privacy practices of Google, please visit the
                                    Google Privacy &amp; Terms web page:&nbsp;<a href="./privacy?hl=en">https://policies.google.com/privacy?hl=en</a>
                                </p>
                            </li>
                            <li>
                                <strong>Facebook</strong>
                                <p>Facebook remarketing service is provided by Facebook Inc.</p>
                                <p>You can learn more about interest-based advertising from Facebook by
                                    visiting this page:&nbsp;<a href="./164968693837950">https://www.facebook.com/help/164968693837950</a>
                                </p>
                                <p>To opt-out from Facebook’s interest-based ads, follow these
                                    instructions from Facebook:<a href="./568137493302217">https://www.facebook.com/help/568137493302217</a>
                                </p>
                                <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural
                                    Advertising established by the Digital Advertising Alliance. You can
                                    also opt-out from Facebook and other participating companies through the
                                    Digital Advertising Alliance in the USA&nbsp;<a href="./choices">http://www.aboutads.info/choices/</a>, the Digital
                                    Advertising Alliance of Canada in Canada&nbsp;<a href="./youradchoices.ca">http://youradchoices.ca/</a>&nbsp;or the European
                                    Interactive Digital Advertising Alliance in Europe&nbsp;<a href="./www.youronlinechoices.eu">http://www.youronlinechoices.eu/</a>,
                                    or opt-out using your mobile device settings.
                                </p>
                                <p>For more information on the privacy practices of Facebook, please visit
                                    Facebook’s Data Policy:&nbsp;<a href="./explanation">https://www.facebook.com/privacy/explanation</a>
                                </p>
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Payments</h4>
                        <p>We may provide paid products and/or services within the Service. In that case, we
                            use third-party services for payment processing (e.g. payment processors).
                        </p>
                        <p>We will not store or collect your payment card details. That information is
                            provided directly to our third-party payment processors whose use of your
                            personal information is governed by their Privacy Policy. These payment
                            processors adhere to the standards set by PCI-DSS as managed by the PCI Security
                            Standards Council, which is a joint effort of brands like Visa, MasterCard,
                            American Express and Discover. PCI-DSS requirements help ensure the secure
                            handling of payment information.
                        </p>
                        <p>The payment processors we work with are:</p>
                        <ul>
                            <li>
                                <strong>Apple Store In-App Payments</strong>
                                <p>Their Privacy Policy can be viewed at&nbsp;<a href="./en-ww">https://www.apple.com/legal/privacy/en-ww/</a>
                                </p>
                            </li>
                            <li>
                                <strong>Google Play In-App Payments</strong>
                                <p>Their Privacy Policy can be viewed at&nbsp;<a href="./privacy3">https://www.google.com/policies/privacy/</a>
                                </p>
                            </li>
                        </ul>
                        <h4 className="mb-3 mt-3">Links to Other Sites</h4>
                        <p>Our Service may contain links to other sites that are not operated by us. If you
                            click a third party link, you will be directed to that third party’s site.
                            We strongly advise you to review the Privacy Policy of every site you visit.
                        </p>
                        <p>We have no control over and assume no responsibility for the content, privacy
                            policies or practices of any third party sites or services.
                        </p>
                        <h4 className="mb-3 mt-3">Children’s Privacy</h4>
                        <p>Our Service does not address anyone under the age of 18 (“Children”).
                        </p>
                        <p>We do not knowingly collect personally identifiable information from anyone under
                            the age of 18. If you are a parent or guardian and you are aware that your Child
                            has provided us with Personal Data, please contact us. If we become aware that
                            we have collected Personal Data from children without verification of parental
                            consent, we take steps to remove that information from our servers.
                        </p>
                        <h4 className="mb-3 mt-3">Changes to This Privacy Policy</h4>
                        <p>We may update our Privacy Policy from time to time. We will notify you of any
                            changes by posting the new Privacy Policy on this page.
                        </p>
                        <p>We will let you know via email and/or a prominent notice on our Service, prior to
                            the change becoming effective and update the “effective date” at the
                            top of this Privacy Policy.
                        </p>
                        <p>You are advised to review this Privacy Policy periodically for any changes.
                            Changes to this Privacy Policy are effective when they are posted on this page.
                        </p>
                        <h4 className="mb-3 mt-3">Contact Us</h4>
                        <p>If you have any questions about this Privacy Policy, would you like to learn more about why, how, and what Personal Data we use, or to request deleting it, please contact us at support@Unipuzz Studio.com.</p>
                    </div>
                </div>
            </div>
      </section>
      
    </Base>
  );
};

export const getStaticProps = async () => {
  const homePage = await getListPage("content/_index.md");
  const { frontmatter } = homePage;
  return {
    props: {
      frontmatter,
    },
  };
};

export default PrivacyPolicy;
